apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-creds-secret
  labels:
    app: minio
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'minio' | base64)
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'minio123' | base64)
  secretkey: bWluaW8xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-console-secret
  labels:
    app: minio
type: Opaque
data:
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: ${CLUSTER_NAME}
  labels:
    app: minio
spec:
  image: minio/minio:RELEASE.2021-03-04T00-53-13Z
  mountPath: /export
  requestAutoCert: true
  # see https://github.com/minio/minio/tree/master/docs/config
  env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: "public"
  - name: MINIO_BROWSER
    value: "off"
  - name : MINIO_API_SELECT_PARQUET
    value: "on"
  pools:
  - servers: 4
    volumesPerServer: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 2000m
        memory: 2Gi
  credsSecret:
    name: ${CLUSTER_NAME}-creds-secret
  console:
    image: minio/console:v0.6.3
    securityContext:
      runAsUser: 1000
      runAsGroup: 2000
      runAsNonRoot: true
    consoleSecret:
      name: ${CLUSTER_NAME}-console-secret
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 1000m
        memory: 512Mi

